spring.application.name=post-service

server.port=9002
server.servlet.context-path=/api/v1/posts

spring.datasource.url=jdbc:postgresql://localhost:5432/post_db
spring.datasource.username=postgres
spring.datasource.password=root
