spring.application.name=user-service

server.port=9003
server.servlet.context-path=/users

spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=root

jwt.secret-key=57B/2nS2UnPsmAFa9tKrQ0bx/FWEoleIu0/eQCR8KfA=

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
